services:
  # Backend API service
  - type: web
    name: ai-examiner-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: / 